export const WALLET = "WALLET";
export const COUNTRY = "COUNTRY";
export const BIDS = "BIDS";
export const RESET_STATUS = "RESET_STATUS";
export const SHOW_CARD_TOKEN = "SHOW_CARD_TOKEN";
export const RESET_APP = "RESET_APP";
export const RESET_BID_DETAILS = "RESET_BID_DETAILS";
export const ASKS = "ASKS";
export const RESET_CONFIRM_KYC  = "RESET_CONFIRM_KYC"
export const GET_CARD_OTPS = "GET_CARD_OTPS";
export const SAVEPIN = "SAVEPIN";
export const RATE_LIMIT = "RATE_LIMIT";
export const FEE_CHECKER_FLAT = "FEE_CHECKER_FLAT";
export const FETCH_CONTACT_INFO = "FETCH_CONTACT_INFO";
export const SHOPPING_ORIGIN = "SHOPPING_ORIGIN";
export const VERIFICATION_DETAILS_KYC = "VERIFICATION_DETAILS_KYC";
export const TRANSACTION_LIST_CARD = "TRANSACTION_LIST_CARD";
export const OTP_TO_BE_VERIFIED = "OTP_TO_BE_VERIFIED";
export const RESET_FEE_CONFIG = "RESET_FEE_CONFIG";
export const RESET_LINKING = "RESET_LINKING";
export const PRE_VERIFY_EMAIL = "PRE_VERIFY_EMAIL";
export const GET_KUDA_BANKS = "GET_KUDA_BANKS";
export const BRIDGE_CARD_FUND = "BRIDGE_CARD_FUND";
export const FREEZE_CARD = "FREEZE_CARD";
export const RESET_CARD_OTPS = "RESET_CARD_OTPS";
export const ACCEPT_KUDA_TERMS = "ACCEPT_KUDA_TERMS";
export const RESET_KYC = "RESET_KYC";
export const CONFIRM_KYC = "CONFIRM_KYC";
export const LOOKUP_ACCOUNT_KUDA = "LOOKUP_ACCOUNT_KUDA";
export const LOOKUP_ACCOUNT_USD = "LOOKUP_ACCOUNT_USD";
export const OTP_VERIFY = "OTP_VERIFY";
export const CARD_UPDATE = "CARD_UPDATE";
export const VCARD_BALANCE = "VCARD_BALANCE";
export const CARD_RETRIEVAL = "CARD_RETRIEVAL";
export const RESET_CARD_SET = "RESET_CARD_SET";
export const CARD_ACTIVATION = "CARD_ACTIVATION";
export const CARD_DELETE = "CARD_DELETE";
export const RESET_VGS = "RESET_VGS";
export const VISA_CARD_PIN_SET = "VISA_CARD_PIN_SET";
export const GET_PIN_TOKEN = "GET_PIN_TOKEN";
export const ASK_SUGGESTIONS = "ASK_SUGGESTIONS";
export const ACCOUNT_MIGRATION = "ACCOUNT_MIGRATION";
export const SWITCH_APP = "SWITCH_APP";
export const NEW_WALLET = "NEW_WALLET";
export const PLAID_ACC_DETAILS = "PLAID_ACC_DETAILS";
export const RESET_LOOK_UP = "RESET_LOOK_UP";
export const ADD_PLAID_ACC = "ADD_PLAID_ACC";
export const TRANSACTION_LIST_ACCOUNT = "TRANSACTION_LIST_ACCOUNT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const USER_ACCOUNTS = "USER_ACCOUNTS";
export const ACH_TYPES = "ACH_TYPES";
export const GET_STARTED = "GET_STARTED";
export const BASE_CONFIGS = "BASE_CONFIGS";
export const CANCEL_EMAIL = "CANCEL_EMAIL";
export const READ_USER_INFO = "READ_USER_INFO";
export const USER_PROFILE = "USER_PROFILE";
export const LOADING = "LOADING";
export const LOADING_USER = "LOADING_USER";
export const ERROR = "ERROR";
export const KYC_VERIFICATION = "KYC_VERIFICATION";
export const WALLET_BALANCE = "WALLET_BALANCE";
export const VERIFICATION_DETAILS = "VERIFICATION_DETAILS";
export const ADD_CURRENT_ASK = "ADD_CURRENT_ASK";
export const ADD_ASK = "ADD_ASK";
export const SUCCESS_CREATED_ASK = "SUCCESS_CREATED_ASK";
export const SUCCESS_EDITED_ASK = "SUCCESS_EDITED_ASK";
export const CONFIGS_INQUIRY = "CONFIGS_INQUIRY";
export const LOADING_CONFIGS = "LOADING_CONFIGS";
export const ON_ADD_BRIDGECARD = "ON_ADD__BRIDGECARD";
export const MY_ASK = "MY_ASK";
export const MY_ASK_DATA = "MY_ASK_DATA";
export const OTHER_ASK_DATA = "OTHER_ASK_DATA";
export const CANCEL_ASK = "CANCEL_ASK";
export const BIDDINGS_ON_ASK = "BIDDINGS_ON_ASK";
export const GET_BID_FEE = "GET_BID_FEE";
export const GET_BRIDGE_CARD = "GET_BRIDGE_CARD";
export const BID_ASK = "BID_ASK";
export const BUY_ASK = "BUY_ASK";
export const BID_BUY_TYPE = "TYPE";
export const BID_REJECTED = "BID_REJECTED";
export const BID_ACCEPTED = "BID_ACCEPTED";
export const LOADING_MESSAGES = " LOADING_MESSAGES";
export const MESSAGES = "MESSSAGES";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const READ_MESSAGE = "READ_MESSAGE";
export const IS_READ = "IS_READ";

export const SAVE_BID_REF = "SAVE_BID_REF";
export const EDIT_ASK_INFO = "EDIT_ASK_INFO";
export const RESET_BIDS = "RESET_BIDS";
export const ASK_INQUIRY = "ASK_INQUIRY";
export const LOADING_WEBSITE = "LOADING_WEBSITE";
export const ASK_LIMIT = "ASK_LIMIT";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const EMPTY_CART = "EMPTY_CART";
export const ADD_CART = "ADD_CART"
export const SUB_CART = "SUB_CART"

//prefentials
export const ASK_ERROR = "ASK_ERROR";
export const BID_ERROR = "BID_ERROR";

export const LINKED_ACCOUNTS = "LINKED_ACCOUNTS";
export const UNLINK_ACCOUNT = " UNLINK_ACCOUNT";

//CHATSnp
export const GET_PRESETS = "GET_PRESETS";
export const GET_CHATLIST = "GET_CHATLIST";
export const CHART_DATA = "CHART_DATA";
export const KUDANGNCHART_DATA = "KUDANGNCHART_DATA";
export const READ_CHAT = "READ_CHAT";
export const SEND_CHAT = "SEND_CHAT";
export const GET_READCHAT = "GET_READCHAT";
export const CHAT_DATA = "CHAT_DATA";
export const NEW_MSG = "NEW_MSG";
export const REFRESH = "REFRESH";
export const ADD_USER_CHAT = "ADDD_USER_CHAT";
export const TRANSACTION_STATUS = "TRANSACTION_STATUS";
export const EXCHANGE_STATUS = "EXCHANGE_STATUS";
export const SET_PICTURE = "SET_PICTURE";
export const BLOGS = "GET_BLOGS";
export const ACCOUNT_TYPES = "ACCOUNT_TYPES";

//AUTH
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const RESET_PASSWORD = "RESET_PASS";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const EMAIL_TO_BE_VERIFIED = "VERIFYING_EMAIL";
export const INITIATE_FORGOT_PASSWORD = "INITIATE_FORGOT_PASSWORD";
export const CAPTHA_PROCESS = "CAPTHA_PROCESS";

// WALLET
export const LOADING_WALLET = "LOADING_WALLET";
export const LOADING_WALLET2 = "LOADING_WALLET2";
export const LOADING_ENQUIRY = "LOADING_ENQUIRY";
export const FEE_CONFIG = "FEE_CONFIG";
export const FEE_CHECKER = "FEE_CHECKER";
export const FUND_WITH_FLW = "FUND_WITH_FLW";
export const FUND_WITH_SILA = "FUND_WITH_SILA";
export const FETCH_ACC_NAME = "FETCH_ACC_NAME";
export const WITHDRAW_NAIRA = "WITHDRAW_NAIRA";
export const WITHDRAW_DOLLAR = "WITHDRAW_DOLLAR";
export const GET_CONFIGS = "GET_CONFIGS";
export const WITHDRAW_DOM = "WITHDRAW_DOM";
export const INSTANT_SETTLEMENT_FEE = "INSTANT_SETTLEMENT_FEE";

// SETTINGS
export const LOADING_SETTINGS = "LOADING_SETTINGS";
export const INITIATE_PIN_SETUP = "INITIATE_PIN_SETUP";
export const SET_PIN = "SET_PIN";
export const INITIATE_PASSWORD_RESET = "INITIATE_PASSWORD_RESET";
export const PASSWORD_RESET = "PASSWORD_RESET";
export const ALL_NOTIFICATIONS = "ALL_NOTIFICATIONS";

// TRANSACTIONS
export const LOADING_TRANSACTION = "LOADING_TRANSACTION";
export const TRANSACTION_LIST = "TRANSACTION_LIST";

// BIDS
export const LOADING_BIDS = "LOADING_BIDS";
export const BID_LIST = "BID_LIST";
export const BID_DETAILS = "BID_DETAILS";
export const CANCEL_BID = "CANCEL_BID";

export const LOADING_BENEFICIARIES = "LOADING_BENEFICIARIES";
export const FETCH_BENEFICIARIES = "FETCH_BENEFICIARIES";
export const FETCH_4TRADER_BENEFICIARIES = "FETCH_4TRADER_BENEFICIARIES";
export const ADD_BENEFICIARY = "ADD_BENEFICIARY";
export const REMOVE_BENEFICIARY = "REMOVE_BENEFICIARY";

export const DEVICE_OTP = "DEVICE_OTP";
export const SEND_PHONE_OTP = "SEND_PHONE_OTP";
export const VERIFY_PHONE_OTP = "VERIFY_PHONE_OTP";
export const VERIFY_PHONE_AUTH = "VERIFY_PHONE_AUTH";
export const UPDATE_PHONE = "UPDATE_PHONE";

export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";

export const MARK_TOUR_GUIDE = "MARK_TOUR_GUIDE";

//IACH
export const IACH = "IACH";
export const IACH_SESSION = "IACH_SESSION";
export const LOADING_IACH = "LOADING_IACH";

//
export const LOADING_BLOG = "LOADING_BLOG";
export const BLOG = "BLOG";
export const DEBIT_CARD_PUSH = "DEBIT_CARD_PUSH";
export const CREATE_DEBIT_CARD_CONTACT = "CREATE_DEBIT_CARD_CONTACT";
export const LOADING_SETTLEMENT = "LOADING_SETTLEMENT";
export const ACTIVATE_INSTANT_SETTLEMENT = "ACTIVATE_INSTANT_SETTLEMENT";
export const SUBMIT_MICRO_DEBIT = "SUBMIT_MICRO_DEBIT";
export const INVOKE_VGS = "INVOKE_VGS";

// EMPLOYEE
export const INVITE_EMPLOYEE = "INVITE_EMPLOYEE";
export const LOADING_EMPLOYEE = "LOADING_EMPLOYEE";
export const FETCH_STAFF_INVITES = "FETCH_STAFF_INVITES";
export const FETCH_COMPANY_INVITES = "FETCH_COMPANY_INVITES";
export const TREAT_INVITE = "TREAT_INVITE";
export const JOIN_COMPANY = "JOIN_COMPANY";
export const TREAT_JOIN_REQUEST = "TREAT_JOIN_REQUEST";
export const GET_JOIN_REQUEST = "GET_JOIN_REQUEST";
export const COMPANIES = "COMPANIES";
export const FETCH_ALL_STAFF = "FETCH_ALL_STAFF";
export const INSTANT_PAYMENT = "INSTANT_PAYMENT";
export const PAYMENT_TRANSACTIONS = "PAYMENT_TRANSACTIONS";
export const KLADOT_CHART = "KLADOT_CHART";

export const CREATE_PLANS = "CREATE_PLANS";
export const UPDATE_PLAN = "UPDATE_PLAN";
export const GET_PLANS = "GET_PLANS";
export const ACTIVATE_PLAN = "ACTIVATE_PLAN";
export const SUSPEND_PLAN = "SUSPEND_PLAN";
export const DELETE_PLAN = "DELETE_PLAN";

export const FETCH_STAFF_SCHEDULE = "FETCH_STAFF_SCHEDULE";
export const CREATE_STAFF_SCHEDULE = "CREATE_STAFF_SCHEDULE";
export const UPDATE_STAFF_SCHEDULE = "UPDATE_STAFF_SCHEDULE";
export const REMOVE_STAFF_SCHEDULE = "REMOVE_STAFF_SCHEDULE";

export const COMPANY_STATISTICS = "COMPANY_STATISTICS";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

export const MIGRATE_TO_PAYEE = "MIGRATE_TO_PAYEE";

export const GET_REFERRALS = "GET_REFERRALS";

export const GET_NOTIFICATION_PREFERENCES = "GET_NOTIFICATION_PREFERENCES";
export const GET_NOTIFICATION_PREFERENCE_CHANNELS =
  "GET_NOTIFICATION_PREFERENCE_CHANNELS";
export const APPLY_NOTIFICATION_PREFERENCE = "APPLY_NOTIFICATION_PREFERENCE";

export const EDIT_FRIENDLY_NAME = "EDIT_FRIENDLY_NAME";

export const US_BENEFICIARIES = "US_BENEFICIARIES";
export const USD_PAYOUT = "USD_PAYOUT";

export const TRANSACTION_VOLUME_ONE = "TRANSACTION_VOLUME_ONE";
export const TRANSACTION_VOLUME_TWO = "TRANSACTION_VOLUME_TWO";
export const TRANSACTION_VOLUME_THREE = "TRANSACTION_VOLUME_THREE";
export const TRANSACTION_VOLUME_FOUR = "TRANSACTION_VOLUME_FOUR";

export const REFEREE_DETAILS = "REFEREE_DETAILS";

export const INITIATE_UNLOCK_ACCOUNT = "INITIATE_UNLOCK_ACCOUNT";

export const SWITCH_TO_PERSONAL = "SWITCH_TO_PERSONAL";

export const JOIN_WAITLIST = "JOIN_WAITLIST";

export const LOADING_CONTACTS = "LOADING_CONTACTS";
export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const CREATE_CONTACT = "CREATE_CONTACT";

export const LOADING_SEND_MONEY = "LOADING_SEND_MONEY";
export const INTRA_BANK_TRANSFER = "INTRA_BANK_TRANSFER";
export const USD_INTRA_BANK_TRANSFER = "INTRA_BANK_TRANSFER";
export const KYC_STATES = "KYC_STATES";
export const LOOKUP_ACCOUNT = "LOOKUP_ACCOUNT";

export const PHONE_NUMBER = "PHONE_NUMBER";

// KUDA TYPES
export const KUDA_ACCOUNT_DETAILS = "KUDA_ACCOUNT_DETAILS";

// PAYMENT Request
export const PAYMENT_REQUEST_LIST = "PAYMENT_REQUEST_LIST";
export const PAYMENT_DETAILS = "PAYMENT_DETAILS";
export const PAYMENT_REQUEST_LOADING = "PAYMENT_REQUEST_LOADING";
export const SAVED_PAYMENT_REQUEST = "SAVED_PAYMENT_REQUEST";
export const LOADING_PAYMENT_REQUEST = "LOADING_PAYMENT_REQUEST";
